# Generated by Django 5.2.4 on 2025-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_class', models.CharField(max_length=120)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
